### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MistakingManx** [Medstar117/HaloWarsDE-Mod-Manager#8]
Would you mind if I made my own, possibly worse mod manager?
Like, I'm sure no one would use one if I made it, but I want to make it solely because I want to add stuff to it.

**Comment by Medstar117** [comment]
If you want to, sure. When I get a moment, I'll add the proper license to this repository.

Or, if you'd like to, make a fork of this repository with your additions and make a PR to contribute? Either way would be fine with me.

It's not good to have multiple standards for doing the exact same thing.

**Comment by MistakingManx** [comment]
It would've been in a different language, since I don't know how to use C or Net.
But, I'm focusing on life instead and yours is fine anyway
